import { generateAIResponse } from '@/services/ai-provider';
import { readGenerationSettings, type GenerationSettings } from '@/lib/gen-settings-store';
import { getInternalAppUrl } from '@/lib/runtime-origin';
import { internalServiceHeaders } from '@/lib/internal-service-auth';
import { ImagePromptModerationError, moderateImagePrompt } from '@/services/image-content-moderation';

type ProviderMode = GenerationSettings['mode'];

export type ParsedImageCommand = {
  prompt: string;
  raw: boolean;
  count?: number;
  provider?: ProviderMode;
};

export type ImageCommandResult = {
  prompt: string;
  originalPrompt: string;
  optimizedPrompt: string | null;
  provider?: string;
  images: string[];
};

export type ImageCommandOptions = {
  scope?: 'public' | 'private';
};

export function canUsePublicImageGeneration(
  access: GenerationSettings['publicImageAccess'],
  isModeratorOrBroadcaster: boolean,
): boolean {
  return access === 'everyone' || (access === 'mods' && isModeratorOrBroadcaster);
}

export function buildPublicImageOverlayMessages(result: ImageCommandResult, username: string) {
  const imageUrl = result.images[0];
  return [
    {
      type: 'pokemon-show-card',
      payload: {
        name: `Generated by @${username}`,
        rarity: 'AI Image',
        number: 'IMG',
        setCode: result.provider,
        imageUrl,
        username,
      },
    },
    {
      type: 'public-image-generated',
      payload: {
        username,
        prompt: result.originalPrompt,
        imageUrl,
        images: result.images,
        provider: result.provider,
      },
    },
  ];
}

function clampCount(value: unknown, fallback: number): number {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) return fallback;
  return Math.max(1, Math.min(4, Math.floor(parsed)));
}

export function parseImageCommand(input: string): ParsedImageCommand {
  let value = String(input || '').replace(/^!img\s*/i, '').trim();
  let raw = false;
  let provider: ProviderMode | undefined;
  let count: number | undefined;

  const consume = (pattern: RegExp, handler: (match: RegExpMatchArray) => void) => {
    const match = value.match(pattern);
    if (!match) return false;
    handler(match);
    value = value.replace(pattern, '').trim();
    return true;
  };

  let changed = true;
  while (changed) {
    changed = false;
    changed = consume(/^--raw\b/i, () => { raw = true; }) || changed;
    changed = consume(/^raw:\s*/i, () => { raw = true; }) || changed;
    changed = consume(/^--count\s+([1-4])\b/i, (match) => { count = clampCount(match[1], 1); }) || changed;
    changed = consume(/^-n\s+([1-4])\b/i, (match) => { count = clampCount(match[1], 1); }) || changed;
    changed = consume(/^--(seaart|eden|perchance|pollinations|free)\b/i, (match) => {
      provider = match[1].toLowerCase() === 'free' ? 'pollinations' : match[1].toLowerCase() as ProviderMode;
    }) || changed;
    changed = consume(/^([1-4])\s+/, (match) => { count = clampCount(match[1], 1); }) || changed;
  }

  return { prompt: value, raw, count, provider };
}

export async function optimizeImagePrompt(
  prompt: string,
  settings: GenerationSettings,
  tenantId?: string,
): Promise<string> {
  const optimized = await generateAIResponse(
    `User idea:\n${prompt}`,
    settings.imagePromptTemplate,
    tenantId,
    { maxTokens: 180, temperature: 0.75 },
  );
  const cleaned = optimized
    .replace(/^["'`\s]+|["'`\s]+$/g, '')
    .replace(/^final prompt:\s*/i, '')
    .trim();
  if (!cleaned || cleaned === 'AI response failed') return prompt;
  return cleaned.slice(0, 3000);
}

export function groundOptimizedImagePrompt(originalPrompt: string, optimizedPrompt: string): string {
  const original = originalPrompt.replace(/\s+/g, ' ').trim();
  const optimized = optimizedPrompt.replace(/\s+/g, ' ').trim();
  if (!optimized || optimized.toLocaleLowerCase() === original.toLocaleLowerCase()) {
    return original;
  }

  return [
    `PRIMARY REQUEST (must be clearly visible): ${original}.`,
    'Create one image that visibly depicts every subject and action in the primary request.',
    'Do not replace the requested subject or action with scenery, symbols, or an unrelated scene.',
    `Additional visual direction: ${optimized}`,
  ].join(' ').slice(0, 3000);
}

export async function runImageCommand(input: string, tenantId: string, options: ImageCommandOptions = {}): Promise<ImageCommandResult> {
  const parsed = parseImageCommand(input);
  if (!parsed.prompt) {
    return {
      prompt: '',
      originalPrompt: '',
      optimizedPrompt: null,
      images: [],
    };
  }

  const settings = await readGenerationSettings(tenantId);
  const scope = options.scope || 'public';
  const moderationEnabled = scope === 'private'
    ? settings.privateContentModeration
    : settings.publicContentModeration;
  if (moderationEnabled) {
    const moderation = await moderateImagePrompt(parsed.prompt, tenantId);
    if (moderation.flagged) {
      throw new ImagePromptModerationError(moderation.categories);
    }
  }
  const shouldOptimize = settings.optimizeImagePrompts && !parsed.raw;
  const optimizedPrompt = shouldOptimize
    ? await optimizeImagePrompt(parsed.prompt, settings, tenantId).catch((error) => {
        console.warn('[Image Command] prompt optimization failed:', error);
        return parsed.prompt;
      })
    : parsed.prompt;
  const finalPrompt = shouldOptimize
    ? groundOptimizedImagePrompt(parsed.prompt, optimizedPrompt)
    : parsed.prompt;

  const imageRes = await fetch(`${getInternalAppUrl()}/api/ai/image`, {
    method: 'POST',
    headers: internalServiceHeaders({ 'Content-Type': 'application/json' }),
    body: JSON.stringify({
      prompt: finalPrompt,
      tenantId,
      model: settings.model || undefined,
      resolution: settings.resolution || undefined,
      numImages: parsed.count || settings.imageCount || 1,
      scope,
      providerParams: {
        lora: settings.lora || undefined,
        loraStrength: settings.lora ? settings.loraStrength : undefined,
        steps: settings.steps,
        cfg: settings.cfg,
        seed: settings.seed,
        ...(parsed.provider ? { providerOverride: parsed.provider } : {}),
      },
      ...(parsed.provider ? { providerOverride: parsed.provider } : {}),
    }),
  });

  if (!imageRes.ok) {
    const errText = await imageRes.text().catch(() => '');
    throw new Error(`Image generation failed: ${imageRes.status} ${errText.slice(0, 400)}`);
  }

  const imageData = await imageRes.json();
  const images = [
    ...(Array.isArray(imageData?.images) ? imageData.images : []),
    imageData?.image,
    imageData?.imageResourceUrl,
    imageData?.data?.image,
  ]
    .map((value) => String(value || '').trim())
    .filter(Boolean)
    .filter((value, index, all) => all.indexOf(value) === index);

  // Prefer durable local copies, while preserving the requested 1-4 results.
  // The former single-item reduction made every multi-image setting appear broken.
  const localImages = images.filter((url) => url.includes('/api/ai/image/file/'));
  const requestedCount = parsed.count || settings.imageCount || 1;
  const finalImages = (localImages.length ? localImages : images).slice(0, requestedCount);

  return {
    prompt: finalPrompt,
    originalPrompt: parsed.prompt,
    optimizedPrompt: finalPrompt !== parsed.prompt ? finalPrompt : null,
    provider: imageData?.provider || parsed.provider || settings.mode,
    images: finalImages,
  };
}
