import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { generateAIResponse } from '../src/services/ai-provider';
import { transcribeAudio } from '../src/services/speech';
import { translateToLanguage } from '../src/services/translation';
import { generateFreeGeminiResponse, isFreeGeminiConfigured, transcribeFreeGeminiAudio } from '../src/services/free-gemini-chat';
import { requestPrivateChatCompletion } from '../src/services/private-chat-ai';
import { AI_PAUSED_MESSAGE } from '../src/services/ai-cost-policy';

test('verified free Gemini serves public/private chat, blocks paid endpoints and bounds failure storms', async t => {
  const dir = mkdtempSync(path.join(tmpdir(), 'free-gemini-'));
  const policy = path.join(dir, 'policy.json');
  const oldPath = process.env.AI_COST_POLICY_PATH;
  const oldKey = process.env.GEMINI_API_KEY;
  process.env.AI_COST_POLICY_PATH = policy;
  process.env.GEMINI_API_KEY = 'unit-test-key-' + Date.now();
  t.after(() => {
    if (oldPath === undefined) delete process.env.AI_COST_POLICY_PATH; else process.env.AI_COST_POLICY_PATH = oldPath;
    if (oldKey === undefined) delete process.env.GEMINI_API_KEY; else process.env.GEMINI_API_KEY = oldKey;
    rmSync(dir, { recursive: true, force: true });
  });
  let calls = 0;
  let status = 200;
  let temperature = 0.7;
  let audioMime = '';
  let payload: any = { candidates: [{ content: { parts: [{ text: 'private reasoning', thought: true }, { text: 'Hello from the free provider.' }] } }] };
  let blocked: Promise<void> | undefined;
  let inFlight = 0;
  let maximumInFlight = 0;
  const prompts: string[] = [];
  t.mock.method(globalThis, 'fetch', async (url: any, init?: RequestInit) => {
    calls++;
    inFlight++;
    maximumInFlight = Math.max(maximumInFlight, inFlight);
    assert.equal(String(url), 'https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash-lite:generateContent');
    assert.equal(new Headers(init?.headers).get('x-goog-api-key'), process.env.GEMINI_API_KEY);
    assert.equal(new Headers(init?.headers).has('authorization'), false);
    assert.equal(init?.redirect, 'error');
    const body = JSON.parse(String(init?.body));
    prompts.push(body.contents[0].parts.at(-1).text);
    temperature = body.generationConfig.temperature;
    audioMime = body.contents[0].parts[0]?.inlineData?.mimeType || '';
    assert.ok(body.generationConfig.maxOutputTokens <= 1200);
    assert.ok(body.contents[0].parts.at(-1).text.length <= 24_000);
    if (blocked) await blocked;
    inFlight--;
    return new Response(JSON.stringify(payload), { status, headers: { 'content-type': 'application/json' } });
  });
  writeFileSync(policy, JSON.stringify({ paidRoutesEnabled: false }));
  assert.equal(await generateAIResponse('Hello'), AI_PAUSED_MESSAGE);
  assert.equal((await translateToLanguage('Hello', 'es')).error, AI_PAUSED_MESSAGE);
  assert.equal((await transcribeAudio('invalid')).provider, 'paused');
  assert.equal(calls, 0, 'having a key is not verification that its project is free');
  writeFileSync(policy, JSON.stringify({ paidRoutesEnabled: false, geminiFreeTierVerified: 'true' }));
  assert.equal(await generateAIResponse('Hello'), AI_PAUSED_MESSAGE);
  assert.equal(calls, 0);
  writeFileSync(policy, JSON.stringify({ paidRoutesEnabled: false, geminiFreeTierVerified: true }));
  assert.equal(await generateAIResponse('Hello'), 'Hello from the free provider.');
  assert.equal((await requestPrivateChatCompletion({ apiKey: 'unused-paid-key', prompt: 'Hello', systemPrompt: 'Be kind.' })).text, 'Hello from the free provider.');
  assert.equal(calls, 2, 'neither public nor private chat called a paid fallback');
  const configuredKey = process.env.GEMINI_API_KEY;
  delete process.env.GEMINI_API_KEY;
  assert.equal(isFreeGeminiConfigured('another-tenant'), false, 'tenant JSON credentials cannot inherit the verified global policy');
  process.env.GEMINI_API_KEY = configuredKey;
  assert.equal((await translateToLanguage('Hello', 'es')).translatedText, 'Hello from the free provider.');
  await generateFreeGeminiResponse('Deterministic selection', '', undefined, { temperature: 0 });
  assert.equal(temperature, 0);
  payload = { promptFeedback: { blockReason: 'SAFETY' } };
  await assert.rejects(generateFreeGeminiResponse('Blocked turn'), { category: 'blocked' });
  payload = { candidates: [{ content: { parts: [{ text: 'This is a complete first sentence. This second sentence is much longer and should not be cut in half.' }] } }] };
  assert.equal(await generateFreeGeminiResponse('Short social reply', '', undefined, { maxCharacters: 45 }), 'This is a complete first sentence.');
  payload = { candidates: [{ content: { parts: [{ text: 'Hello from the free provider.' }] } }] };
  assert.equal(await generateFreeGeminiResponse('Another tenant still works'), 'Hello from the free provider.');
  const callsBeforeInvalidAudio = calls;
  await assert.rejects(transcribeFreeGeminiAudio('not-audio'), { category: 'invalid_audio' });
  await assert.rejects(transcribeFreeGeminiAudio('A'.repeat(700_001)), { category: 'invalid_audio' });
  assert.equal(calls, callsBeforeInvalidAudio);
  const wav = Buffer.alloc(44); wav.write('RIFF'); wav.write('WAVE', 8);
  assert.equal((await transcribeAudio(wav.toString('base64'))).provider, 'gemini-free');
  assert.equal(audioMime, 'audio/wav');
  const webm = Buffer.alloc(16); webm.set([0x1a, 0x45, 0xdf, 0xa3]);
  await transcribeFreeGeminiAudio(webm.toString('base64'));
  assert.equal(audioMime, 'audio/webm');
  assert.equal(temperature, 0);
  let release!: () => void;
  blocked = new Promise<void>(resolve => { release = resolve; });
  const active = generateFreeGeminiResponse('Long response');
  const queued = generateFreeGeminiResponse('Concurrent response');
  const queuedSecond = generateFreeGeminiResponse('Second queued response');
  await assert.rejects(generateFreeGeminiResponse('Queue overflow'), { category: 'busy' });
  release();
  await Promise.all([active, queued, queuedSecond]);
  blocked = undefined;
  assert.equal(maximumInFlight, 1);
  assert.deepEqual(prompts.slice(-3), ['Long response', 'Concurrent response', 'Second queued response']);
  blocked = new Promise<void>(resolve => { release = resolve; });
  const held = generateFreeGeminiResponse('Held response');
  await assert.rejects(generateFreeGeminiResponse('Expired queued turn'), { category: 'busy' });
  const beforeRelease = calls;
  release();
  await held;
  blocked = undefined;
  assert.equal(calls, beforeRelease, 'expired queued prompts must never be sent later');
  blocked = new Promise<void>(resolve => { release = resolve; });
  status = 429;
  const quotaActive = assert.rejects(generateFreeGeminiResponse('Quota active'), { category: 'quota' });
  const quotaQueued = assert.rejects(generateFreeGeminiResponse('Quota queued'), { category: 'quota' });
  await new Promise<void>(resolve => setImmediate(resolve));
  const beforeQuotaRelease = calls;
  release();
  await Promise.all([quotaActive, quotaQueued]);
  blocked = undefined;
  assert.equal(calls, beforeQuotaRelease, 'queued requests respect cooldown created by the preceding response');
  status = 429;
  await assert.rejects(generateAIResponse('Quota'), { category: 'quota' });
  const callsAtQuota = calls;
  await Promise.all(Array.from({ length: 20 }, () => assert.rejects(generateAIResponse('Retry'), { category: 'quota' })));
  assert.equal(calls, callsAtQuota, 'quota cooldown prevents retry storms and paid fallback');
  process.env.GEMINI_API_KEY += '-replacement';
  status = 200;
  assert.equal(await generateAIResponse('New key'), 'Hello from the free provider.');
});
